[input]
base_directory = "output"
html_selector = "main"

[[input.files]]
path = "about.html"
url = "/about"
title = "About"

[[input.files]]
path = "projects.html"
url = "/projects"
title = "Projects"

[[input.files]]
path = "first-impressions-with-software-development-on-termux.html"
url = "/first-impressions-with-software-development-on-termux.html"
title = "First Impressions With Software Development On Termux"

[[input.files]]
path = "developing-software-on-android-using-termux.html"
url = "/developing-software-on-android-using-termux.html"
title = "Developing Software On Android Using Termux"

[[input.files]]
path = "my-homelab.html"
url = "/my-homelab.html"
title = "My HomeLab"

[[input.files]]
path = "bookstack-the-self-hosted-wiki.html"
url = "/bookstack-the-self-hosted-wiki.html"
title = "BookStack - The Self-Hosted Wiki"

[[input.files]]
path = "simple-side-scroller.html"
url = "/simple-side-scroller.html"
title = "Simple Side Scroller"